"""Shared AgentState for the AstaLink LangGraph pipeline.

Every node reads and partially updates this state. Fields that are unknown
at a given pipeline stage are typed as Optional and start as None.

The `audit_id` is generated by N1 (intent classifier) and propagated through
every downstream node and Supabase write, so a single trace can be reconstructed
from logs + audit_log table.

Reducer notes
-------------
``entities`` is annotated with ``operator.or_`` so the three parallel analysis
nodes (n2a/n2b/n2c) can each write their own sub-key in the same superstep
without triggering LangGraph's INVALID_CONCURRENT_GRAPH_UPDATE error.
"""
from __future__ import annotations

import operator
import uuid
from enum import StrEnum
from typing import Annotated, Any, TypedDict

from langchain_core.messages import BaseMessage


class LegalStatus(StrEnum):
    APPROVED = "approved"
    PARTIAL = "partial"
    REJECTED = "rejected"
    REJECTED_AFTER_MAX_REVISIONS = "rejected_after_max_revisions"


class UserApproval(StrEnum):
    APPROVED = "approved"
    REJECTED = "rejected"


class AgentState(TypedDict, total=False):
    """Shared state across every LangGraph node.

    `total=False` so partial updates from individual nodes type-check;
    keys absent from a node's return value are left untouched by LangGraph."""

    # Trace
    audit_id: str

    # Set by the API entry point (agent.py / whatsapp.py) before the first
    # invoke — must be declared here or LangGraph silently drops them, since
    # StateGraph(AgentState) only tracks channels present in this schema.
    _user_id: str | None
    _workspace_id: str | None

    # Conversation
    messages: list[BaseMessage]

    # N1 — Intent
    intent: str | None
    # Annotated with dict-union reducer so parallel analysis nodes (n2a/n2b/n2c)
    # can each write their sub-key in the same superstep without conflict.
    entities: Annotated[dict[str, Any], operator.or_]
    # True when N1 couldn't confidently classify the message (unknown intent
    # or confidence < CONFIDENCE_FLOOR) — routes straight to END instead of
    # burning a full optimizer/legal cycle on entities that were never
    # extracted. Always set explicitly by intent_node (never left absent) so
    # a stale True can't leak in from an earlier turn on the same thread.
    _needs_clarification: bool

    # L0 — Layer 0 capital allocation (cash/stocks/business). Written once
    # by l0_allocation; None until that node runs. Includes the terminal
    # INSUFFICIENT_DATA output — a valid result, not an error.
    layer0_result: dict[str, Any] | None

    # N2/N5 — Allocation
    allocation_plan: dict[str, Any] | None
    revision_count: int

    # N3 — Legal
    legal_status: LegalStatus | None
    legal_citations: list[dict[str, Any]]

    # N6 — HITL
    user_approval: UserApproval | None

    # N7 — Execution
    transactions: list[dict[str, Any]]

    # Cross-cutting
    errors: list[dict[str, Any]]


def new_state() -> AgentState:
    """Build a fresh AgentState for a new pipeline run.

    audit_id is generated here once and immutable for the lifetime of the run."""
    return AgentState(
        audit_id=str(uuid.uuid4()),
        messages=[],
        intent=None,
        entities={},
        layer0_result=None,
        allocation_plan=None,
        revision_count=0,
        legal_status=None,
        legal_citations=[],
        user_approval=None,
        transactions=[],
        errors=[],
    )
